#### Why is Candace Parker so exceptional?

This project focused on the analysis of 2017 season of wnba league. To take things further, we have decided to conduct further analysis of what makes Candace Parker so good?

In [3]:
import pandas as pd 
cp = pd.read_csv('../data/wnba_clean.csv')

In [10]:
cp = pd.read_csv('../data/wnba_clean.csv')
cp.head(60)

,Name,Team,Pos,Height,Weight,BMI,Birth_Place,Birthdate,Age,College,...,OREB,DREB,REB,AST,STL,BLK,TO,PTS,DD2,TD3
0,Aerial Powers,DAL,F,183,71,21.200991,US,"January 17, 1994",23,Michigan State,...,6,22,28,12,3,6,12,93,0,0
1,Alana Beard,LA,G/F,185,73,21.329438,US,"May 14, 1982",35,Duke,...,19,82,101,72,63,13,40,217,0,0
2,Alex Bentley,CON,G,170,69,23.875433,US,"October 27, 1990",26,Penn State,...,4,36,40,78,22,3,24,218,0,0
3,Alex Montgomery,SAN,G/F,185,84,24.543462,US,"December 11, 1988",28,Georgia Tech,...,35,134,169,65,20,10,38,188,2,0
4,Alexis Jones,MIN,G,175,78,25.469388,US,"August 5, 1994",23,Baylor,...,3,9,12,12,7,0,14,50,0,0
5,Alexis Peterson,SEA,G,170,63,21.799308,US,"June 20, 1995",22,Syracuse,...,3,13,16,11,5,0,11,26,0,0
6,Alexis Prince,PHO,G,188,81,22.917610,US,"February 5, 1994",23,Baylor,...,1,14,15,5,4,3,3,24,0,0
7,Allie Quigley,CHI,G,178,64,20.199470,US,"June 20, 1986",31,DePaul,...,9,83,92,95,20,13,59,442,0,0
8,Allisha Gray,DAL,G,185,76,22.205990,US,"October 20, 1992",24,South Carolina,...,52,75,127,40,47,19,37,395,0,0
9,Allison Hightower,WAS,G,178,77,24.302487,US,"June 4, 1988",29,LSU,...,3,7,10,10,5,0,2,36,0,0
10,Alysha Clark,SEA,F,180,76,23.456790,US,"July 7, 1987",30,Middle Tennessee,...,29,97,126,50,22,4,32,244,0,0
11,Alyssa Thomas,CON,F,188,84,23.766410,US,"December 4, 1992",24,Maryland,...,34,158,192,136,48,11,87,399,4,0
12,Amanda Zahui B.,NY,C,196,113,29.414827,SE,"August 9, 1993",24,Minnesota,...,5,18,23,7,4,5,12,51,0,0
13,Amber Harris,CHI,F,196,88,22.907122,US,"January 16, 1988",29,Xavier,...,12,28,40,5,3,9,6,41,0,0
14,Aneika Henry,ATL,F/C,193,87,23.356332,JM,"February 13, 1986",31,Florida,...,0,4,4,1,2,0,3,8,0,0
15,Angel Robinson,PHO,F/C,198,88,22.446689,US,"August 30, 1995",21,Arizona State,...,16,42,58,8,1,11,16,58,0,0
16,Asia Taylor,WAS,F,185,76,22.205990,US,"August 22, 1991",26,Louisville,...,16,21,37,9,5,2,10,31,0,0
17,Bashaara Graves,CHI,F,188,91,25.746944,US,"March 17, 1994",23,Tennessee,...,4,13,17,3,0,1,3,19,0,0
18,Breanna Lewis,DAL,C,196,93,24.208663,US,"June 22, 1994",23,Kansas State,...,2,7,9,2,0,0,7,7,0,0
19,Breanna Stewart,SEA,F/C,193,77,20.671696,US,"August 27, 1994",22,Connecticut,...,43,206,249,78,29,47,68,584,8,0
20,Bria Hartley,NY,G,173,66,22.052190,US,"September 30, 1992",24,Connecticut,...,7,50,57,58,15,5,44,217,0,0
21,Bria Holmes,ATL,G,185,77,22.498174,US,"April 19, 1994",23,West Virginia,...,29,56,85,52,23,7,31,235,0,0
22,Briann January,IND,G,173,65,21.718066,US,"November 1, 1987",29,Arizona State,...,12,25,37,98,23,4,53,238,0,0
23,Brionna Jones,CON,F,191,104,28.507990,US,"December 18, 1995",21,Maryland,...,11,14,25,2,7,1,7,44,0,0
24,Brittany Boyd,NY,G,175,71,23.183673,US,"November 6, 1993",23,UC Berkeley,...,3,5,8,5,3,0,2,26,0,0
25,Brittney Griner,PHO,C,206,93,21.915355,US,"October 18, 1990",26,Baylor,...,43,129,172,39,13,54,52,461,6,0
26,Brittney Sykes,ATL,G,175,66,21.551020,US,"July 2, 1994",23,Rutgers,...,25,94,119,59,18,17,49,397,1,0
27,Camille Little,PHO,F,188,82,23.200543,US,"January 18, 1985",32,North Carolina,...,42,71,113,42,28,13,50,228,0,0
28,Candace Parker,LA,F/C,193,79,21.208623,US,"April 19, 1986",31,Tennessee,...,37,205,242,127,43,53,80,494,10,1
29,Candice Dupree,IND,F,188,81,22.917610,US,"February 25, 1984",33,Temple,...,31,124,155,47,28,12,42,435,2,0
30,Cappie Pondexter,CHI,G,175,73,23.836735,US,"July 1, 1983",34,Rutgers,...,10,59,69,104,17,5,56,250,2,0
31,Carolyn Swords,SEA,C,198,95,24.232221,US,"July 19, 1989",28,Boston College,...,10,29,39,9,5,4,22,54,0,0
32,Cayla George,PHO,C,193,87,23.356332,AU,"April 20, 1987",30,Georgia,...,10,71,81,15,9,11,13,100,1,0
33,Chelsea Gray,LA,G,180,77,23.765432,US,"August 10, 1992",25,Duke,...,19,80,99,132,29,7,61,456,1,0
34,Cheyenne Parker,CHI,F,193,86,23.087868,US,"August 22, 1992",25,Middle Tennessee,...,31,47,78,13,8,15,21,87,0,0
35,Clarissa dos Santos,SAN,C,185,89,26.004383,BR,"October 3, 1988",28,Brazil,...,3,7,10,7,1,1,5,17,0,0
36,Courtney Paris,DAL,C,193,113,30.336385,US,"September 21, 1987",29,Oklahoma,...,28,34,62,5,6,8,18,70,0,0
37,Courtney Vandersloot,CHI,G,173,66,22.052190,US,"August 2, 1989",28,Gonzaga,...,13,75,88,175,22,5,64,255,10,0
38,Courtney Williams,CON,G,173,62,20.715694,US,"November 5, 1994",22,South Florida,...,38,84,122,60,15,6,39,375,1,0
39,Crystal Langhorne,SEA,F/C,188,84,23.766410,US,"October 27, 1986",30,Maryland,...,35,140,175,46,16,11,50,370,2,0
40,Damiris Dantas,ATL,C,191,89,24.396261,BR,"November 17, 1992",24,Brazil,...,29,84,113,19,17,18,26,254,0,0
41,Danielle Adams,CON,F/C,185,108,31.555880,US,"February 19, 1989",28,Texas A&M,...,6,4,10,4,4,4,7,49,0,0
42,Danielle Robinson,PHO,G,175,57,18.612245,US,"October 5, 1989",27,Oklahoma,...,13,73,86,106,33,4,58,209,0,0
43,Dearica Hamby,SAN,F,191,86,23.573915,US,"June 11, 1993",24,Wake Forest,...,48,91,139,32,29,8,43,253,1,0
44,Devereaux Peters,IND,F,188,79,22.351743,US,"August 10, 1989",28,Notre Dame,...,8,69,77,76,16,9,56,514,0,0
45,Diana Taurasi,PHO,G,183,74,22.096808,US,"November 6, 1982",34,Connecticut,...,31,98,129,32,20,31,28,376,3,0
46,Elena Delle Donne,WAS,G/F,196,85,22.126197,US,"May 9, 1989",28,Delaware,...,99,116,215,43,32,64,36,317,4,0
47,Elizabeth Williams,ATL,F/C,191,87,23.848030,US,"June 23, 1993",24,Duke,...,35,61,96,5,5,4,21,128,0,0
48,Emma Cannon,PHO,F,188,86,24.332277,US,"January 6, 1989",28,Central Florida,...,33,72,105,52,21,27,30,252,1,0
49,Emma Meesseman,WAS,C,193,83,22.282477,BE,"May 13, 1993",24,Belgium,...,23,58,81,70,34,5,30,259,0,0
50,Epiphanny Prince,NY,G,175,81,26.448980,US,"November 1, 1988",28,Rutgers,...,17,44,61,5,4,8,17,88,0,0
51,Erica Wheeler,IND,G,170,65,22.491349,US,"February 5, 1991",26,Rutgers,...,11,57,68,117,38,1,68,336,0,0
52,Érika de Souza,SAN,C,196,86,22.386506,BR,"September 3, 1982",34,Brazil,...,58,74,132,35,18,7,37,159,0,0
53,Erlana Larkins,IND,F,185,93,27.173119,US,"February 4, 1986",31,North Carolina,...,9,26,35,24,11,8,13,102,0,0
54,Essence Carson,LA,G/F,183,74,22.096808,US,"July 28, 1986",31,Rutgers,...,7,2,9,0,1,3,5,13,0,0
55,Evelyn Akhator,DAL,F,191,82,22.477454,NG,"March 2, 1995",22,Kentucky,...,73,199,272,50,37,13,67,442,13,0
56,Glory Johnson,DAL,F,191,77,21.106878,US,"July 27, 1990",27,Tennessee,...,0,3,3,1,0,0,4,9,0,0
57,Imani Boyette,ATL,C,201,88,21.781639,US,"November 10, 1992",24,Texas,...,43,75,118,14,9,23,22,127,1,0
58,Isabelle Harrison,SAN,C,191,83,22.751569,US,"September 27, 1993",23,Kentucky,...,66,134,200,46,26,24,63,364,5,0
59,Ivory Latta,WAS,G,168,63,22.321429,US,"September 25, 1984",32,North Carolina,...,7,20,27,49,12,1,22,245,0,0

In [1]:
def quant_(col, quant,relative):
    if relative==True:
        names=wnba.loc[(wnba[col]/wnba["MIN"]) > (wnba[col]/wnba["MIN"]).quantile(quant)]["Name"]
    else:
        names=wnba.loc[wnba[col] > wnba[col].quantile(quant)]["Name"]
    return list(names)
def count_names(cols, quant, relative):
    count={}
    for col in cols:
        for name in quant_(col,quant,relative):
            if name in count.keys():
                count[name]+=1
            else:
                count[name]=1
    count={k: v for k, v in sorted(count.items(), key=lambda item: item[1],reverse=True)}
    return count

In [ ]:
count_names('Height', )